[[redirects]]
  from = "/end-of-lyfe-toolkit"
  to = "/toolkit"
  status = 301

[[redirects]]
  from = "/toolkit"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200