// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prchqgbqfpqittpmxsdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByY2hxZ2JxZnBxaXR0cG14c2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNjM3NDgsImV4cCI6MjA2NzkzOTc0OH0.B-03iEzphKoRk6V-hRZYPTh3t13RmPHJGPrSh0fD7dQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});