// This file is automatically generated. Do not edit it directly.
import { getSupabaseClient } from '@/utils/supabase-singleton';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use the singleton instance to prevent multiple clients
export const supabase = getSupabaseClient();